LOG:  database system was shut down at 2016-04-07 19:32:52 MSK
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 5439? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "*"
FATAL:  could not create any TCP/IP sockets
LOG:  database system was shut down at 2016-04-08 01:22:21 MSK
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "matrices" already exists
STATEMENT:  CREATE TABLE  matrices
	(
	  id serial NOT NULL,
	  name text NOT NULL,
	  ncols integer NOT NULL,
	  nrows integer NOT NULL,
	  row_indeces integer[],
	  col_indeces integer[],
	  vals real[],
	  CONSTRAINT matrices_pkey PRIMARY KEY (name)
	)
	WITH (
	  OIDS=FALSE
	);
ERROR:  relation "matrices_col_indeces_idx" already exists
STATEMENT:  CREATE INDEX  matrices_col_indeces_idx
	  ON matrices
	  USING btree
	  (col_indeces);
ERROR:  relation "matrices_id_idx" already exists
STATEMENT:  CREATE INDEX  matrices_id_idx
	  ON matrices
	  USING btree
	  (id);
ERROR:  relation "matrices_name_idx" already exists
STATEMENT:  CREATE INDEX  matrices_name_idx
	  ON matrices
	  USING btree
	  (name COLLATE pg_catalog."default");
ERROR:  relation "matrices_row_indeces_idx" already exists
STATEMENT:  CREATE INDEX  matrices_row_indeces_idx
	  ON matrices
	  USING btree
	  (row_indeces);
ERROR:  relation "matrices_vals_idx" already exists
STATEMENT:  CREATE INDEX  matrices_vals_idx
	  ON matrices
	  USING btree
	  (vals);
ERROR:  relation "vectors" already exists
STATEMENT:  CREATE TABLE  vectors
	(
	  id serial NOT NULL,
	  name text NOT NULL,
	  size integer NOT NULL,
	  indeces integer[],
	  vals real[],
	  CONSTRAINT vectors_pkey PRIMARY KEY (name)
	)
	WITH (
	  OIDS=FALSE
	);
ERROR:  relation "vectors_id_idx" already exists
STATEMENT:  CREATE INDEX  vectors_id_idx
	  ON vectors
	  USING btree
	  (id);
ERROR:  relation "vectors_indeces_idx" already exists
STATEMENT:  CREATE INDEX  vectors_indeces_idx
	  ON vectors
	  USING btree
	  (indeces);
ERROR:  relation "vectors_name_idx" already exists
STATEMENT:  CREATE INDEX  vectors_name_idx
	  ON vectors
	  USING btree
	  (name COLLATE pg_catalog."default");
ERROR:  relation "vectors_size_idx" already exists
STATEMENT:  CREATE INDEX  vectors_size_idx
	  ON vectors
	  USING btree
	  (size);
ERROR:  relation "vectors_vals_idx" already exists
STATEMENT:  CREATE INDEX  vectors_vals_idx
	  ON vectors
	  USING btree
	  (vals);
ERROR:  relation "params" already exists
STATEMENT:  CREATE TABLE  params
	(
	  id serial NOT NULL,
	  solver_id integer,
	  vals text[],
	  CONSTRAINT params_pkey PRIMARY KEY (id)
	)
	WITH (
	  OIDS=FALSE
	);
ERROR:  relation "params_id_idx" already exists
STATEMENT:  CREATE INDEX  params_id_idx
	  ON params
	  USING btree
	  (id);
ERROR:  relation "params_solver_id_idx" already exists
STATEMENT:  CREATE INDEX  params_solver_id_idx
	  ON params
	  USING btree
	  (solver_id);
ERROR:  relation "params_vals_idx" already exists
STATEMENT:  CREATE INDEX  params_vals_idx
	  ON params
	  USING btree
	  (vals COLLATE pg_catalog."default");
ERROR:  relation "solutions" already exists
STATEMENT:  CREATE TABLE  solutions
	(
	  matrix_id integer NOT NULL,
	  vector_id integer NOT NULL,
	  param_id integer NOT NULL,
	  solution_vector_id integer NOT NULL,
	  CONSTRAINT solutions_pkey PRIMARY KEY (matrix_id, vector_id, param_id)
	)
	WITH (
	  OIDS=FALSE
	);
ERROR:  relation "solutions_matrix_id_idx" already exists
STATEMENT:  CREATE INDEX  solutions_matrix_id_idx
	  ON solutions
	  USING btree
	  (matrix_id);
ERROR:  relation "solutions_param_id_idx" already exists
STATEMENT:  CREATE INDEX  solutions_param_id_idx
	  ON solutions
	  USING btree
	  (param_id);
ERROR:  relation "solutions_vector_id_idx" already exists
STATEMENT:  CREATE INDEX  solutions_vector_id_idx
	  ON solutions
	  USING btree
	  (vector_id);
ERROR:  relation "solutions_solution_vector_id_idx" already exists
STATEMENT:  CREATE INDEX  solutions_solution_vector_id_idx
	  ON solutions
	  USING btree
	  (solution_vector_id);
ERROR:  relation "solvers" already exists
STATEMENT:  CREATE TABLE  solvers
	(
	  id serial NOT NULL,
	  name text NOT NULL,
	  CONSTRAINT solvers_pkey PRIMARY KEY (name)
	)
	WITH (
	  OIDS=FALSE
	);
ERROR:  relation "solvers_id_idx" already exists
STATEMENT:  CREATE INDEX  solvers_id_idx
	  ON solvers
	  USING btree
	  (id);
ERROR:  unrecognized configuration parameter "row_security"
STATEMENT:  SET row_security = off;
ERROR:  could not open file "base/16384/16387": Permission denied
STATEMENT:  INSERT INTO matrices (id, name, ncols, nrows, row_indeces, col_indeces, vals) VALUES (1, 'mat1', 3, 3, '{0,1,2}', '{0,1,2}', '{5,5,5}');
ERROR:  could not open file "base/16384/16387": Permission denied
STATEMENT:  INSERT INTO matrices (id, name, ncols, nrows, row_indeces, col_indeces, vals) VALUES (2, 'mat2', 5, 5, '{0,1,2,3,4}', '{0,1,2,3,4}', '{5,5,5,5,5}');
ERROR:  could not open file "base/16384/16387": Permission denied
STATEMENT:  INSERT INTO matrices (id, name, ncols, nrows, row_indeces, col_indeces, vals) VALUES (3, 'mat3', 10, 10, '{0,1,2,3,4,5,6,7,8,9}', '{0,1,2,3,4,5,6,7,8,9}', '{1,1,1,1,1,1,1,1,1,1}');
ERROR:  could not open file "base/16384/16387": Permission denied
STATEMENT:  INSERT INTO matrices (id, name, ncols, nrows, row_indeces, col_indeces, vals) VALUES (5, 'mat7', 3, 3, '{0,1,2}', '{0,1,2}', '{5,5,10}');
ERROR:  could not open file "base/16384/16385": Permission denied
STATEMENT:  SELECT pg_catalog.setval('matrices_id_seq', 5, true);
ERROR:  could not open file "base/16384/16409": Permission denied
STATEMENT:  INSERT INTO params (id, solver_id, vals) VALUES (1, 1, '{2.1}');
ERROR:  could not open file "base/16384/16409": Permission denied
STATEMENT:  INSERT INTO params (id, solver_id, vals) VALUES (2, 1, '{2.71}');
ERROR:  could not open file "base/16384/16409": Permission denied
STATEMENT:  INSERT INTO params (id, solver_id, vals) VALUES (3, 1, '{1e-006}');
ERROR:  could not open file "base/16384/16409": Permission denied
STATEMENT:  INSERT INTO params (id, solver_id, vals) VALUES (4, -1, '{1e-006}');
ERROR:  could not open file "base/16384/16407": Permission denied
STATEMENT:  SELECT pg_catalog.setval('params_id_seq', 4, true);
ERROR:  could not open file "base/16384/16418": Permission denied
STATEMENT:  INSERT INTO solutions (matrix_id, vector_id, param_id, solution_vector_id) VALUES (1, 3, 3, 8);
ERROR:  could not open file "base/16384/16418": Permission denied
STATEMENT:  INSERT INTO solutions (matrix_id, vector_id, param_id, solution_vector_id) VALUES (5, 3, 3, 9);
ERROR:  could not open file "base/16384/16418": Permission denied
STATEMENT:  INSERT INTO solutions (matrix_id, vector_id, param_id, solution_vector_id) VALUES (1, 10, 3, 11);
ERROR:  could not open file "base/16384/16425": Permission denied
STATEMENT:  INSERT INTO solvers (id, name) VALUES (1, 'GaussSolver');
ERROR:  could not open file "base/16384/16423": Permission denied
STATEMENT:  SELECT pg_catalog.setval('solvers_id_seq', 1, true);
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (1, 'vec1', 10, '{0,1,2,3,4,5,6,7,8,9}', '{0,1,2,3,4,5,6,7,8,9}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (3, 'vec5', 3, '{0,1,2}', '{0,1,2}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (7, 'sol1', 3, '{0,1,2}', '{0,0.200000003,0.400000006}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (8, 'solution5', 3, '{0,1,2}', '{0,0.200000003,0.400000006}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (9, 'solut7', 3, '{0,1,2}', '{0,0.200000003,0.200000003}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (10, 'vec12', 3, '{0,1,2}', '{0,1,2}');
ERROR:  could not open file "base/16384/16398": Permission denied
STATEMENT:  INSERT INTO vectors (id, name, size, indeces, vals) VALUES (11, 'solution10', 3, '{0,1,2}', '{0,0.200000003,0.400000006}');
ERROR:  could not open file "base/16384/16396": Permission denied
STATEMENT:  SELECT pg_catalog.setval('vectors_id_seq', 11, true);
ERROR:  could not create file "base/16384/11792_fsm": File exists
CONTEXT:  automatic vacuum of table "matdb.pg_catalog.pg_attribute"
ERROR:  could not create file "base/16384/11792_fsm": File exists
CONTEXT:  automatic vacuum of table "matdb.pg_catalog.pg_attribute"
ERROR:  could not create file "base/16384/11792_fsm": File exists
CONTEXT:  automatic vacuum of table "matdb.pg_catalog.pg_attribute"
ERROR:  could not create file "base/16384/11792_fsm": File exists
CONTEXT:  automatic vacuum of table "matdb.pg_catalog.pg_attribute"
LOG:  WAL writer process (PID 3324) exited with exit code 1
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-04-08 01:25:56 MSK
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/1801478
LOG:  invalid magic number 0000 in log segment 000000010000000000000001, offset 8544256
LOG:  redo done at 0/18246C8
LOG:  last completed transaction was at log time 2016-04-08 01:26:39.597+04
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  checkpointer process (PID 3972) exited with exit code 1
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-04-08 01:30:39 MSK
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/1825838
LOG:  redo is not required
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  checkpointer process (PID 4064) exited with exit code 1
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-04-08 01:30:44 MSK
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/18258A0
LOG:  redo is not required
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  database system was shut down at 2016-04-08 01:32:26 MSK
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-04-08 01:32:33 MSK
LOG:  database system is ready to accept connections
FATAL:  the database system is starting up
LOG:  autovacuum launcher started
ERROR:  unrecognized configuration parameter "row_security"
STATEMENT:  SET row_security = off;
LOG:  database system was shut down at 2016-06-25 16:26:04 MSK
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-06-25 16:26:14 MSK
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
WARNING:  pgstat wait timeout
WARNING:  pgstat wait timeout
LOG:  database system was shut down at 2017-10-13 10:28:24 GMT
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-10-13 15:06:08 MSK
FATAL:  the database system is starting up
LOG:  database system is ready to accept connections
FATAL:  the database system is starting up
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2017-10-13 15:06:29 MSK
FATAL:  the database system is starting up
LOG:  database system is ready to accept connections
FATAL:  the database system is starting up
LOG:  autovacuum launcher started
ERROR:  type "id" does not exist at character 76
STATEMENT:  CREATE TABLE IF NOT EXISTS roads
	(
	  id serial PRIMARY KEY,
	  city_from id NOT NULL,
	  city_to id   NOT NULL,
	  CONSTRAINT roads_city_from_fkey FOREIGN KEY (city_from)
	      REFERENCES cities (id) MATCH SIMPLE
	      ON UPDATE NO ACTION ON DELETE NO ACTION,
	  CONSTRAINT roads_city_to_fkey FOREIGN KEY (city_to)
	      REFERENCES cities (id) MATCH SIMPLE
	      ON UPDATE NO ACTION ON DELETE NO ACTION
	);
ERROR:  relation "dictionary" does not exist
CONTEXT:  SQL statement "ALTER TABLE dictionary
	        ADD CONSTRAINT roads_city_from_fkey FOREIGN KEY (streamNameMask)
	        REFERENCES cities (id) MATCH SIMPLE
	        ON UPDATE NO ACTION ON DELETE NO ACTION"
	PL/pgSQL function inline_code_block line 4 at SQL statement
STATEMENT:  DO $$
	BEGIN
	    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'roads_city_from_fkey') THEN
	        ALTER TABLE dictionary
	        ADD CONSTRAINT roads_city_from_fkey FOREIGN KEY (streamNameMask)
	        REFERENCES cities (id) MATCH SIMPLE
	        ON UPDATE NO ACTION ON DELETE NO ACTION;
	    END IF;
	END;
	$$;
ERROR:  relation "dictionary" does not exist
CONTEXT:  SQL statement "ALTER TABLE dictionary
	        ADD CONSTRAINT roads_city_from_fkey FOREIGN KEY (streamNameMask)
	        REFERENCES cities (id) MATCH SIMPLE
	        ON UPDATE NO ACTION ON DELETE NO ACTION"
	PL/pgSQL function inline_code_block line 4 at SQL statement
STATEMENT:  DO $$
	BEGIN
	    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'roads_city_to_fkey') THEN
	        ALTER TABLE dictionary
	        ADD CONSTRAINT roads_city_from_fkey FOREIGN KEY (streamNameMask)
	        REFERENCES cities (id) MATCH SIMPLE
	        ON UPDATE NO ACTION ON DELETE NO ACTION;
	    END IF;
	END;
	$$;
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
